on:
  create:


jobs:
  placeholder:
    name: Placeholder
    if: >-
      (github.event_name == 'create' &&
       startsWith(github.ref, 'refs/tags/')) ||
       github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Print Context
        run: |
          echo "${{ toJson(github.event) }}"
      - name: Get Version
        id: get_version
        uses: actions/github-script@v7
        with:
          script: |
            console.log(`context: ${JSON.stringify(context)}`);
